# -*- coding: utf-8 -*-
"""etl_causa_mortes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_h4FQvd-UxCO2Y0wH08T2zPk9_DW6Gl
"""

import pandas as pd
import os

path = "/root/.cache/kagglehub/datasets/syedaeman2212/deaths-and-causes/versions/1"
file = os.listdir(path)[0]

df = pd.read_csv(f"{path}/{file}")
df



df.info()
df.isnull().sum()
df.duplicated().sum()

# renomeando colunas conforme o banco de dados
df_ods = df.rename(columns = {
    "Year": "ano",
    "Country": "regiao",
    "Gender": "genero",
    "Age_Group" : "faixa_etaria",
    "Cause_of_Death":"causa_morte",
    "Number_of_Deaths":"num_mortes",
    'Mortality_Rate_per_1000': 'mortality_rate_per_1000'
    })

# ajustando tipos
df_ods['ano'] = df_ods['ano'].astype(int)
df_ods['num_mortes'] = df_ods['num_mortes'].astype(int)
df_ods['mortality_rate_per_1000'] = df_ods['mortality_rate_per_1000'].astype(float)

df_ods.to_csv("ods_deaths_causes.csv", index=False)

# conexao supabase
from google.colab import userdata

supabase_url = userdata.get('SUPABASE')

# criando engine
from sqlalchemy import create_engine, text
engine = create_engine(supabase_url, pool_pre_ping = True)
engine.connect()