# -*- coding: utf-8 -*-
"""etl_causa_mortes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_h4FQvd-UxCO2Y0wH08T2zPk9_DW6Gl
"""

import pandas as pd
import os

path = "/root/.cache/kagglehub/datasets/syedaeman2212/deaths-and-causes/versions/1"
file = os.listdir(path)[0]

df = pd.read_csv(f"{path}/{file}")
df



df.info()
df.isnull().sum()
df.duplicated().sum()

# renomeando colunas conforme o banco de dados
df_ods = df.rename(columns = {
    "Year": "ano",
    "Country": "regiao",
    "Gender": "genero",
    "Age_Group" : "faixa_etaria",
    "Cause_of_Death":"causa_morte",
    "Number_of_Deaths":"num_mortes",
    'Mortality_Rate_per_1000': 'mortality_rate_per_1000'
    })

# ajustando tipos
df_ods['ano'] = df_ods['ano'].astype(int)
df_ods['num_mortes'] = df_ods['num_mortes'].astype(int)
df_ods['mortality_rate_per_1000'] = df_ods['mortality_rate_per_1000'].astype(float)


# conexao supabase
from google.colab import userdata

supabase_url = userdata.get('SUPABASE')

# criando engine
from sqlalchemy import create_engine, text
engine = create_engine(supabase_url, pool_pre_ping = True)
engine.connect()

# pegando ods do banco
df_ods = pd.read_sql("SELECT * FROM ods_death_causes", engine)

# dimensão causa
dim_causa = (df_ods[['causa_morte']]
             .drop_duplicates()
             .reset_index(drop=True))
dim_causa = dim_causa.rename(columns={'causa_morte': 'descricao'})
dim_causa.to_csv("dim_causa.csv", index=False)

# dimensão genero
dim_genero = (df_ods[['genero']]
              .drop_duplicates()
              .reset_index(drop=True))
dim_genero = dim_genero.rename(columns={'genero': 'descricao'})
dim_genero.to_csv("dim_genero.csv", index=False)

# dimensão faixa etaria
dim_grupo_idade = (df_ods[['faixa_etaria']]
                   .drop_duplicates()
                   .reset_index(drop=True))
dim_grupo_idade = dim_grupo_idade.rename(columns={'faixa_etaria': 'descricao'})
dim_grupo_idade.to_csv("dim_grupo_idade.csv", index=False)

#dimensão região
dim_regiao = (df_ods[['regiao']]
              .drop_duplicates()
              .reset_index(drop=True))
dim_regiao = dim_regiao.rename(columns={'regiao': 'descricao'})
dim_regiao.to_csv("dim_regiao.csv", index=False)